version: '3'
# define all services
services:
  frontend:
    image: node:10
    restart: always
    ports:
      - 8080:8080
    command: bash -c "npm install && npm run start"
    working_dir: /src/
    volumes:
      - ./crypto-frontend/:/src:delegated # improve speed for hot reloading
    environment:
      HOST: 0.0.0.0
      CHOKIDAR_USEPOLLING: 'true'
      VUE_APP_BACKEND_URL: 'backend'
    networks:
      crypto_network:
          ipv4_address: 172.29.1.1
  backend:
    image: python:3.8-slim-buster
    restart: always
    ports:
      - 5000:5000
    command: bash -c "pip3 install -r requirements.txt && python3 app.py"
    working_dir: /app/
    volumes: 
      - ./crypto-backend/:/app:delegated
    networks:
      crypto_network:
          ipv4_address: 172.29.1.2
  # cakephp:
  #   # we want to use the image which is build from our Dockerfile
  #   image: php:7.2-apache
  #   command: bash -c "apachectl -D FOREGROUND"
  #   # apache is running on port 80 but we want to expose this to port 4000 on our local machine
  #   restart: always
  #   ports:
  #     - "5601:80"
  #   volumes:
  #     - .:/var/www/html/
  #   # add vue js development code volume
  #   #-- WARNING!!!:: SSL certificates will be used which are on the host server in given path. Make sure in case the certificates names got changes, you change them here also
  #     # - ./server_testing.crt:/etc/apache2/ssl-certs/server.crt
  #     # - ./server_testing.key:/etc/apache2/ssl-certs/server.key
    #   networks:
  #     crypto_network:
  #         ipv4_address: 172.29.1.3
  corsanywhere:
      image: redocly/cors-anywhere
      ports:
          - "8000:8000"
      environment: 
          PORT: 8000
      networks:
        crypto_network:
            ipv4_address: 172.29.1.4
networks:
  crypto_network:
      ipam:
          driver: default
          config:
              - subnet: 172.29.0.0/16